# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.
#
require 'cucumber/rails'
require 'capybara/cucumber'
require 'selenium-webdriver'
require 'email_spec'
require 'email_spec/cucumber'
require 'simplecov'
SimpleCov.start

Before do
  ActionMailer::Base.deliveries.clear
  BrevoEmail.deliveries = []
end


Capybara.register_driver :selenium_chrome_headless do |app|
  options = Selenium::WebDriver::Chrome::Options.new
  options.add_argument('--headless')
  options.add_argument('--disable-gpu')
  options.add_argument('--window-size=1280,800')


  Capybara::Selenium::Driver.new(app, browser: :chrome, options: options)
end

Capybara.default_driver = :rack_test
Capybara.javascript_driver = :selenium_chrome_headless


Capybara.default_max_wait_time = 5


ActionController::Base.allow_rescue = false


begin
  DatabaseCleaner.strategy = :truncation
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

Before do
  DatabaseCleaner.start
end

After do
  DatabaseCleaner.clean
end

Cucumber::Rails::Database.javascript_strategy = :truncation
