require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/equipment_records", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EquipmentRecord. As you add validations to EquipmentRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EquipmentRecord.create! valid_attributes
      get equipment_records_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      equipment_record = EquipmentRecord.create! valid_attributes
      get equipment_record_url(equipment_record)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_equipment_record_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      equipment_record = EquipmentRecord.create! valid_attributes
      get edit_equipment_record_url(equipment_record)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EquipmentRecord" do
        expect {
          post equipment_records_url, params: { equipment_record: valid_attributes }
        }.to change(EquipmentRecord, :count).by(1)
      end

      it "redirects to the created equipment_record" do
        post equipment_records_url, params: { equipment_record: valid_attributes }
        expect(response).to redirect_to(equipment_record_url(EquipmentRecord.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EquipmentRecord" do
        expect {
          post equipment_records_url, params: { equipment_record: invalid_attributes }
        }.to change(EquipmentRecord, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post equipment_records_url, params: { equipment_record: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested equipment_record" do
        equipment_record = EquipmentRecord.create! valid_attributes
        patch equipment_record_url(equipment_record), params: { equipment_record: new_attributes }
        equipment_record.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the equipment_record" do
        equipment_record = EquipmentRecord.create! valid_attributes
        patch equipment_record_url(equipment_record), params: { equipment_record: new_attributes }
        equipment_record.reload
        expect(response).to redirect_to(equipment_record_url(equipment_record))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        equipment_record = EquipmentRecord.create! valid_attributes
        patch equipment_record_url(equipment_record), params: { equipment_record: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested equipment_record" do
      equipment_record = EquipmentRecord.create! valid_attributes
      expect {
        delete equipment_record_url(equipment_record)
      }.to change(EquipmentRecord, :count).by(-1)
    end

    it "redirects to the equipment_records list" do
      equipment_record = EquipmentRecord.create! valid_attributes
      delete equipment_record_url(equipment_record)
      expect(response).to redirect_to(equipment_records_url)
    end
  end
end
